// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function FileExists(arg1:string):Promise<boolean>;

export function FileSave(arg1:main.Notdir):Promise<void>;

export function FileSaveWithDialog(arg1:main.Notdir):Promise<void>;

export function GetInitialData():Promise<Array<main.NotdirBase>>;

export function MultiSelection():Promise<Array<main.FileInfo>>;

export function NotdirFileOpen(arg1:any):Promise<main.Notdir>;

export function RemoveNotdirsInList(arg1:Array<any>):Promise<void>;

export function RunFile(arg1:string):Promise<void>;

export function SaveNotdirToDb(arg1:main.Notdir):Promise<void>;

export function ShowMessageDialog(arg1:frontend.MessageDialogOptions):Promise<any>;
