// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FileExists(arg1:string):Promise<boolean>;

export function FileOpen(arg1:string):Promise<void>;

export function FileSave(arg1:main.Notdir):Promise<void>;

export function FileSaveWithDialog(arg1:main.Notdir):Promise<void>;

export function MultiSelection():Promise<Array<main.FileInfo>>;

export function NotdirFileOpen():Promise<main.Notdir>;
