// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileOpen(arg1) {
  return window['go']['main']['App']['FileOpen'](arg1);
}

export function FileSave(arg1) {
  return window['go']['main']['App']['FileSave'](arg1);
}

export function MultiSelection() {
  return window['go']['main']['App']['MultiSelection']();
}
