// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function FileSave(arg1) {
  return window['go']['main']['App']['FileSave'](arg1);
}

export function FileSaveWithDialog(arg1) {
  return window['go']['main']['App']['FileSaveWithDialog'](arg1);
}

export function GetInitialData() {
  return window['go']['main']['App']['GetInitialData']();
}

export function MultiSelection() {
  return window['go']['main']['App']['MultiSelection']();
}

export function NotdirFileOpen(arg1) {
  return window['go']['main']['App']['NotdirFileOpen'](arg1);
}

export function RemoveNotdirInList(arg1) {
  return window['go']['main']['App']['RemoveNotdirInList'](arg1);
}

export function RunFile(arg1) {
  return window['go']['main']['App']['RunFile'](arg1);
}

export function SaveNotdirToDb(arg1) {
  return window['go']['main']['App']['SaveNotdirToDb'](arg1);
}

export function ShowMessageDialog(arg1) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1);
}
